[package]
name = "elite-dashboard-api"
version = "0.1.0"
edition = "2021"

[dependencies]
humantime = "2.1.0"
log = "0.4.25"
fern = "0.7.1"
axum = "0.8.1"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
